/*
| ast statements.
|
| FIXME use concat with astExpressions require
*/
module.exports =
[
	'jion$ast_and',
	'ast_arrayLiteral',
	'ast_assign',
	'ast_boolean',
	'ast_block',
	'ast_call',
	'ast_check',
	'ast_comma',
	'ast_comment',
	'ast_condition',
	'ast_continue',
	'ast_delete',
	'ast_differs',
	'ast_dot',
	'ast_equals',
	'ast_fail',
	'ast_for',
	'ast_forIn',
	'ast_func',
	'ast_greaterThan',
	'ast_if',
	'ast_instanceof',
	'ast_lessThan',
	'ast_member',
	'ast_multiply',
	'ast_multiplyAssign',
	'ast_new',
	'ast_not',
	'ast_null',
	'ast_number',
	'ast_objLiteral',
	'ast_or',
	'ast_plus',
	'ast_plusAssign',
	'ast_preIncrement',
	'ast_return',
	'ast_string',
	'ast_switch',
	'ast_typeof',
	'ast_var',
	'ast_varDec'
];
